[package]
name = "fireflow-core"
version = { workspace = true }
edition = { workspace = true }
description = """
Core library code for fireflow.
"""

[dependencies]
derive_more.workspace = true
derive_more.features = [
    "from",
    "into",
    "display",
    "from_str",
    "as_ref",
    "add",
    "mul",
    "into_iterator"
]

chrono = { workspace = true, features = ["clock"] }
thiserror = { workspace = true }
regex = { workspace = true }
derive-new = { workspace = true }
itertools = { workspace = true }
num_enum = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
bigdecimal = { workspace = true }
ambassador = { workspace = true }
unicase = { workspace = true }
hashbrown = { workspace = true }
bytemuck = { workspace = true }
fireflow-types = { path = "../fireflow-types" }
serde = { workspace = true, features = ["derive"], optional = true }
ndarray = { workspace = true }
polars-buffer = { workspace = true }
nonempty-collections = { workspace = true }
crc-fast = { workspace = true }
type_families = { path = "../type_families" }
fireflow-core-proc = { path = "../fireflow-core-proc" }
pyo3 = { workspace = true, optional = true }
numpy = { workspace = true, optional = true }

[dev-dependencies]
proptest = { workspace = true }
proptest-derive = { workspace = true }
assert_matches = { workspace = true }
fireflow-types = { path = "../fireflow-types", features = ["testutil"] }

[features]
serde = [
    "dep:serde",
    "ndarray/serde",
    "bigdecimal/serde",
    "chrono/serde",
    "fireflow-types/serde",
    "nonempty-collections/serde",
    "hashbrown/serde"
]
python = [
    "dep:pyo3",
    "dep:numpy",
    "fireflow-types/python",
]

[lints]
workspace = true