[package]
name = "fireflow-core-proc"
version.workspace = true
edition.workspace = true

[dependencies]
syn = { workspace = true, features = ["derive", "parsing"] }
quote = { workspace = true }
nonempty = { path = "../nonempty", features = ["python"] }

[lib]
proc-macro = true

[lints]
workspace = true