[package]
name = "fireflow-types"
version = { workspace = true }
edition = { workspace = true }
description = """
Simple types and constants used throughout other fireflow crates.
"""

[dependencies]
derive_more = { workspace = true, features = ["from", "into", "display"] }
thiserror = { workspace = true }
itertools = { workspace = true }
const_format = { workspace = true }
pyo3 = { workspace = true, optional = true }
phf = { workspace = true, features = ["macros", "unicase"] }
unicase = { workspace = true }
nonempty-collections = { workspace = true }
fireflow-core-proc = { path = "../fireflow-core-proc", optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[build-dependencies]
phf = { version = "0.13.1", default-features = false, features = ["unicase"] }
phf_codegen = "0.13.1"
unicase = { workspace = true }

[features]
python = ["dep:pyo3", "dep:fireflow-core-proc"]
serde = ["dep:serde"]

[lints]
workspace = true