[package]
name = "fireflow-types"
version = { workspace = true }
edition = { workspace = true }
description = """
Simple types and constants used throughout other fireflow crates.
"""

[dependencies]
derive_more = { workspace = true, features = ["from", "into", "display"] }
thiserror = { workspace = true }
const_format = { workspace = true }
pyo3 = { workspace = true, optional = true, features = ["macros", "hashbrown"] }
phf = { workspace = true, features = ["macros", "unicase"] }
unicase = { workspace = true }
bigdecimal = { workspace = true }
nonempty-collections = { workspace = true }
ambassador = { workspace = true }
derive-new = { workspace = true }
fireflow-core-proc = { path = "../fireflow-core-proc", optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
num_enum = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
regex = { workspace = true }
itertools = { workspace = true }
hashbrown = { workspace = true }

[build-dependencies]
phf = { version = "0.13.1", default-features = false, features = ["unicase"] }
phf_codegen = "0.13.1"
unicase = { workspace = true }

[features]
python = ["dep:pyo3", "dep:fireflow-core-proc"]
serde = ["dep:serde"]
testutil = ["dep:proptest", "dep:proptest-derive"]

[lints]
workspace = true