[workspace]
resolver = "2"
members = [
  "crates/*",
  "pyreflow",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
chrono = "0.4.40"
itertools = "0.14.0"
num_enum = "0.7.4"
num-traits = "0.2.19"
num-derive = "0.4.2"
bigdecimal = "0.4.8"
derive_more = "2.0.1"
derive-new = "0.7.0"
nalgebra = "0.33.2"
nonempty = "0.11.0"
polars = { version = "0.49.0", features = ["dtype-u8", "dtype-u16", "fmt"] }
pyo3 = "0.25.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
missing_panics_doc = "allow"
missing_errors_doc = "allow"

# restrinction lints
shadow_reuse = "warn"
shadow_unrelated = "warn"
absolute_paths = "warn"
# arithmetic_side_effects = "warn"
# as_conversions = "warn"
as_pointer_underscore = "warn"
as_underscore = "warn"
cfg_not_test = "warn"
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
decimal_literal_representation = "warn"