[package]
name = "fireflow-python-proc"
version.workspace = true
edition.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true, features = ["from", "as_ref", "display"] }
syn = { workspace = true, features = ["extra-traits"] }
itertools = { workspace = true }
nonempty-collections = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
const_format = { workspace = true }
fireflow-types = { path = "../fireflow-types", features = ["python"] }

[lib]
proc-macro = true

[lints]
workspace = true