[package]
name = "fireflow-python-proc"
version.workspace = true
edition.workspace = true

[dependencies]
syn = { workspace = true, features = ["extra-traits"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
fireflow-python-types = { path = "../fireflow-python-types" }

[lib]
proc-macro = true

[lints]
workspace = true