[package]
name = "fireflow-python"
version = { workspace = true }
edition = { workspace = true }
description = """
Python-specific code for fireflow.
"""

[dependencies]
fireflow-core = { path = "../fireflow-core", features = ["python"] }
fireflow-python-proc = { path = "../fireflow-python-proc" }
chrono = { workspace = true }
derive_more = { workspace = true, features = ["from", "into"] }
pyo3 = { workspace = true }
pyo3-polars = { workspace = true }
type_families = { path = "../type_families" }

[lints]
workspace = true