[package]
name = "pyreflow"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "pyreflow"
crate-type = ["cdylib"]

[dependencies]
fireflow-core = { path = "../crates/fireflow-core", features = ["python"] }
fireflow-types = { path = "../crates/fireflow-types", features = ["python"] }
fireflow-python = { path = "../crates/fireflow-python" }

pyo3.workspace = true
pyo3.features = [
    "multiple-pymethods",
    "chrono",
    "bigdecimal",
    "hashbrown"
]