[project]
name = "pyreflow"
description = "Fully-compliant Flow Cytometry Standard (FCS) read/write library"
readme = "README.md"
# TODO 3.11 is the lower bound for now since this is the first version to
# support exception groups
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    'Operating System :: POSIX :: Linux',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: MacOS',
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed",
]
dynamic = ["version"]
dependencies = [
    "polars>=1.26.0,<2",
    # This is needed for pyo3-polars to work. 18.x is the first version which
    # does not require setuptools which would add extra complexity here and
    # (hopefully) is not necessary
    "pyarrow>=18.0.0",
    # Include 1.x series since flowkit does not yet work with 2.x. This specific
    # version should have wheels that don't require distutils
    "numpy>=1.26,<3",
]

[project.optional-dependencies]
pydantic = [
    "pydantic>=2,<3"
]

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[dependency-groups]
all = [
    { include-group = "dev" },
    { include-group = "lint" },
    { include-group = "testing" },
    # { include-group = "bench" },
    { include-group = "docs" },
]
dev = ["maturin>=1,<2"]
lint = [
    { include-group = "dev" },
    "mypy[faster-cache]>=1.19,<2",
    "ruff>=0.14,<1",
]
testing = [
    { include-group = "dev" },
    "pytest>=8.4,<9",
]
# bench = [
#     { include-group = "dev" },
#     "flowio>=1.4.0",
#     "fcsparser>=0.2.8",
#     "plotnine>=0.15",
#     "jinja2>=3.1.6",
# ]
docs = [
    { include-group = "dev" },
    "sphinx==9.1.0",
    "sphinx_toolbox==4.2.0",
    "pydata-sphinx-theme==0.21.0",
]

[tool.maturin]
python-source = "python"
module-name = "pyreflow._pyreflow"
features = ["pyo3/extension-module"]

[tool.mypy]
warn_return_any = true

disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true

strict_equality = true
extra_checks = true

check_untyped_defs = true

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 20