name: "CI"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'pyreflow/docs/**'


jobs:
  test-python-and-os:
    runs-on: ${{ matrix.os }}-latest
    name: test with Python = ${{ matrix.py-ver }} and OS = ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        py-ver:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.91
        with:
          components: clippy,rustfmt

      - uses: Swatinem/rust-cache@v2

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.py-ver }}
          activate-environment: true

      - run: make all-dev

  test-msrv:
    name: test MSRV

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11

      - name: resolve MSRV
        id: resolve-msrv
        run: echo MSRV=`uv run python -c 'import tomllib; print(tomllib.load(open("Cargo.toml", "rb"))["workspace"]["package"]["rust-version"])'` >> $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy,rustfmt
          toolchain: ${{ steps.test-msrv.outputs.MSRV }}

      - uses: Swatinem/rust-cache@v2

      - run: make all-dev
