name: "CI"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'pyreflow/docs/**'

jobs:
  test-python-and-os:
    runs-on: ${{ matrix.os }}
    name: test with Python = ${{ matrix.py-ver }} and OS = ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - windows-2025-VS2026
        py-ver:
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: dtolnay/rust-toolchain@1.95.0
        with:
          components: clippy,rustfmt

      - uses: Swatinem/rust-cache@v2.9.1
        with:
          key: ${{ matrix.py-ver }}

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.py-ver }}

      - run: |
          make all-dev
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: |-
            ${{ case(
              contains(matrix.os, 'windows'), '-Clinker=lld-link.exe',
              ''
            ) }}

  test-msrv:
    name: test minimum supported rust version

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: 3.12

      - name: resolve MSRV
        id: resolve-msrv
        run: echo MSRV=`uv run python -c 'import tomllib; print(tomllib.load(open("Cargo.toml", "rb"))["workspace"]["package"]["rust-version"])'` >> $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy,rustfmt
          toolchain: ${{ steps.resolve-msrv.outputs.MSRV }}

      - uses: Swatinem/rust-cache@v2.9.1

      - run: |
          make all-dev
