name: "CI"

on:
  push:
    paths-ignore:
      - '**.md'
      - 'pyreflow/docs/**'


jobs:
  test-python-and-os:
    runs-on: ${{ matrix.os }}-latest
    name: test with Python impl = ${{ matrix.py-version }} and OS = ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
          - windows
        py-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.91
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - uses: astral-sh/setup-uv@v6
        with:
          py-version: ${{ matrix.py-version }}

      - run: make all-dev
