name: "Publish Documentation"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-tags: true

      - uses: dtolnay/rust-toolchain@1.95.0

      - uses: Swatinem/rust-cache@v2.9.1

      - uses: astral-sh/setup-uv@v8.1.0

      - name: Install graphviz
        run: sudo apt install -y graphviz

      - name: Build docs
        run: make all-docs

      - name: Checkout docs branch
        uses: actions/checkout@v6.0.2
        with:
          ref: nist-pages
          # very important, otherwise new docs will be obliterated with 'git clean'
          clean: false

      - name: Remove old docs
        run: |
          rm -rf en

      - name: Move html docs to root
        run: |
          echo "moving and listing stuff"
          ls pyreflow/docs/build_all
          mv pyreflow/docs/build_all/* ./
          touch en/.nojekyll
          ls en

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
