name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: astral-sh/setup-uv@v6

      - name: Install graphviz
        run: sudo apt install -y graphviz

      - name: Build docs
        run: make docs

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: nist-pages
          directory: pyreflow/docs
