name: "Build Documentation"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.8
        with:
          docs-folder: pyreflow/docs/
          formats: |-
            epub
            pdf
