name: "Documentation"

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: astral-sh/setup-uv@v6

      - name: Install graphviz
        run: sudo apt install -y graphviz

      - name: Build docs
        run: make docs

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: nist-pages

      - name: Remove old docs
        run: |
          rm -rf _images _sources _static
          rm -f *.html *.js *.inv .buildinto .nojekyll

      - name: Move html docs to root
        run: mv pyreflow/docs/build/html/* ./

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
